[2024-05-11T12:58:33.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T12:58:33.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_v03.greet scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T12:58:33.463+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_v03.greet scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T12:58:33.464+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-05-11T12:58:33.481+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2024-05-10 00:00:00+00:00
[2024-05-11T12:58:33.491+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13939) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-11T12:58:33.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_v03', 'greet', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag_taskflow_api.py', '--cfg-path', '/tmp/tmps525faz4']
[2024-05-11T12:58:33.494+0000] {standard_task_runner.py:63} INFO - Started process 13940 to run task
[2024-05-11T12:58:33.495+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask greet
[2024-05-11T12:58:33.565+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_taskflow_v03.greet scheduled__2024-05-10T00:00:00+00:00 [running]> on host 48bfb4afd9cd
[2024-05-11T12:58:33.644+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'name'), 'surname': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'surname'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 181, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 171, in render_template
    return value.resolve(context)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 436, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v03 with key="name" is not found!
[2024-05-11T12:58:33.661+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 181, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 171, in render_template
    return value.resolve(context)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 436, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at dag_with_taskflow_v03 with key="name" is not found!
[2024-05-11T12:58:33.667+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_taskflow_v03, task_id=greet, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20240511T125833, end_date=20240511T125833
[2024-05-11T12:58:33.682+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task greet (XComArg result from get_name at dag_with_taskflow_v03 with key="name" is not found!; 13940)
[2024-05-11T12:58:33.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T12:58:33.744+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T12:58:33.747+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
