[2024-05-11T12:32:14.627+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T12:32:14.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_test_dag_v04.greet scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T12:32:14.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_test_dag_v04.greet scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-11T12:32:14.731+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-11T12:32:14.761+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet> on 2024-05-10 00:00:00+00:00
[2024-05-11T12:32:14.777+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12838) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-11T12:32:14.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'python_test_dag_v04', 'greet', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag_test.py', '--cfg-path', '/tmp/tmpe9dl40kn']
[2024-05-11T12:32:14.781+0000] {standard_task_runner.py:63} INFO - Started process 12839 to run task
[2024-05-11T12:32:14.781+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask greet
[2024-05-11T12:32:14.945+0000] {task_command.py:426} INFO - Running <TaskInstance: python_test_dag_v04.greet scheduled__2024-05-10T00:00:00+00:00 [running]> on host 48bfb4afd9cd
[2024-05-11T12:32:15.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='edo' AIRFLOW_CTX_DAG_ID='python_test_dag_v04' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-11T12:32:15.165+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T12:32:15.213+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T12:32:15.227+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/python_operator_dag_test.py", line 11, in make_hello
    name = task_instance.xcoms_pull(task_id = 'get_name')
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'. Did you mean: 'xcom_pull'?
[2024-05-11T12:32:15.261+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=python_test_dag_v04, task_id=greet, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20240511T123214, end_date=20240511T123215
[2024-05-11T12:32:15.424+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 12839)
[2024-05-11T12:32:15.541+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T12:32:15.654+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T12:32:15.675+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
