[2024-05-10T16:40:38.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T16:40:38.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.task3 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T16:40:38.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.task3 scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T16:40:38.346+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-10T16:40:38.426+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task3> on 2024-05-09 00:00:00+00:00
[2024-05-10T16:40:38.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'task3', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpf7o24je8']
[2024-05-10T16:40:38.531+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask task3
[2024-05-10T16:40:38.543+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=686) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T16:40:38.546+0000] {standard_task_runner.py:63} INFO - Started process 689 to run task
[2024-05-10T16:40:38.728+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_dag_v3.task3 scheduled__2024-05-09T00:00:00+00:00 [running]> on host 48bfb4afd9cd
[2024-05-10T16:40:38.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='edo' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-10T16:40:38.989+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T16:40:39.045+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-10T16:40:39.059+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'third one matey']
[2024-05-10T16:40:39.089+0000] {subprocess.py:86} INFO - Output:
[2024-05-10T16:40:39.094+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: third: command not found
[2024-05-10T16:40:39.096+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-10T16:40:39.109+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T16:40:39.157+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-10T16:40:39.174+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag_v3, task_id=task3, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240510T164038, end_date=20240510T164039
[2024-05-10T16:40:39.222+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task task3 (Bash command failed. The command returned a non-zero exit code 127.; 689)
[2024-05-10T16:40:39.250+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T16:40:39.293+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T16:40:39.302+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
